### ISSUE TITLE
[Broken Link] GraphQL Fake seems to be broken

### ISSUE THREAD

**Issue by francisbrito** [APIs-guru/graphql-apis#20]
The site is returning `502` status code.

**Comment by IvanGoncharov** [comment]
@francisbrito You right, thanks for reporting it.
I will wait a couple of days to see maybe it's only temporary and remove it.

**Comment by francisbrito** [comment]
Alright

**Comment by millette** [comment]
Still down.

**Comment by IvanGoncharov** [comment]
@millette Thanks for the ping 👍 
Deleted ❌
