### ISSUE TITLE
Unsure where to add http://gdom.graphene-python.org/graphql

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/graphql-apis#5]
[DOM Traversing and Scraping using GraphQL](http://gdom.graphene-python.org/graphql?query=%7B%0A++page%28url%3A%22http%3A%2F%2Fnews.ycombinator.com%22%29+%7B%0A++++items%3A+query%28selector%3A%22tr.athing%22%29+%7B%0A++++++rank%3A+text%28selector%3A%22td+span.rank%22%29%0A++++++title%3A+text%28selector%3A%22td.title+a%22%29%0A++++++sitebit%3A+text%28selector%3A%22span.comhead+a%22%29%0A++++++url%3A+attr%28selector%3A%22td.title+a%22%2C+name%3A%22href%22%29%0A++++++attrs%3A+next+%7B%0A+++++++++score%3A+text%28selector%3A%22span.score%22%29%0A+++++++++user%3A+text%28selector%3A%22a%3Aeq%280%29%22%29%0A+++++++++comments%3A+text%28selector%3A%22a%3Aeq%282%29%22%29%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D)

It's more of a utility than a demonstration, but I don't think it quite meets the standard of an official API.

Repository [here](https://github.com/syrusakbary/gdom).

**Comment by MikeRalphson** [comment]
One option would be to merge the lists together and have a column denoting the type of API?

**Comment by IvanGoncharov** [comment]
I think it qualifies under official for now. When more public GraphQL appears we will need to rethink the structure and maybe extract `Utility` category.

> One option would be to merge the lists together and have a column denoting the type of API?

Big tables look intimidating to me 😨  Plus I think mixing Demo APIs with others is a bad idea.
